package ru.smartflex.djf;

public enum FormStepEnum {

    BEFORE_CREATE,
    BEFORE_REMOVE,
    AFTER_DATA_INIT_LOADING,
    BEFORE_READ_DATA,
    DATA_INIT_LOADING_PROCESS,
    AFTER_DATA_RELOADING,
    FORM_WAS_SAVED_SUCCESSFULLY
}
